version: '3'
services:
  db:
    image: postgres:15
    container_name: Database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Generator
    volumes:
      - .Docker/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  front:
    image: geradorfront
    restart: always
    ports:
      - "3000:3000"
    